---
title: "Complaint"
author: "William Bryan Milstead"
date: "Sunday, February 15, 2015"
output: html_document
---
<!---
library(knitr)
knit('ComplaintHistory.rmd')
-->
The Story
-------------------------

* On January 16, 2015 I flew from Providence RI USA to Santiago Chile on American Airlines.
* On February 7, 2015 I attempted attempted to use the return portion of the trip and here the saga begins.
* The morning of my flight I attempted to use the American Airlines Online Check in service and was told I need to check in at the airport
* I arrived at the airport two hours before my flight and attempted to check in at the check in kiosk and was told to see an agent.
* When I saw the agent she told me that I had a penalty of U.S. $592.12 (371.200 pesos Chilenos) in order to board the flight.
* The agent could not explain what the charge was for nor could her supervisor, Luis Gajardo.
* I requested that Luis Gajardo call the office for an explanation but he refused saying that he was the supervisor and would make no calls and that if I wanted to take my flight I would need to pay the penalty.
* In order not to miss my flight I agreed to pay but then the agent and later supervisor had difficulties in charging my debit card.  It took the Luis Gajardo over an hour to finally get the charge on my card during which time my flight left and I was booked on a later flight-thus losing my connections.
* Upon return to the U.S. I have attempted to protest the charge but am having great difficulty getting any information from American Airlines.
* American Airlines has yet to tell me what the charge was for, when the penalty was incurred, or who authorized the charge.
* It is very difficult to contact American Airlines.  There is no direct number to call.  The only option is to use a form on their website that does not keep track history and limits user input to 1500 characters.  Therefore I am creating this document to keep track of the interactions.
* Trying to deal with American Airlines Custormer Relations is frustrating and somewhat kafakesque.  As you can see from the correspondence below each attempt to get an answer from American Airlines results in blame shifting and obfuscation. It would be nice if they could just tell me what the charge was for and why they will not refund it. I have the impression that their strategy is to continue to misdirect inquiries until the customer just give up.
* This document is available here: https://github.com/willbmisled/AmericanAirlines/blob/master/ComplaintHistory.md or http://tinyurl.com/ksmblhv

Correspondence
-------------------------
Below is the Correspondence with American Airlines by date.

February 10, 2015-First Communication sent to AA.com
-------------------------
#My message to AA.com on http://www.aa.com/contactAA/viewEmailFormAccess.do?eventName=customerRelations
On Feb. 7 I attempted to use the AA online check in for a return flight from Santiago Chile.  The online check in I was asked me to supply some additional information such as my home address and my middle name.  The online checkin was unsuccessful and was told I need to check in at the airport.  When I arrived at the airport I was told that since I added my middle name to the ticket I was to be charged an additional $592.12 to reissue the ticket. The online check in did not warn me that supplying additional information that it requested would make expensive changes to my ticket nor did it warn me that the charges would have to be paid in order to use my ticket.   Under protest I agreed to pay with the understanding I could protest the charges by connecting to AA.com with the inflight wireless (a service that was not functioning on my flight).  Unfortunately, it took over an hour for the ticket agent to figure out how to charge a debit card so my flilght was missed and I was put on a later flight.

I protest the charge of $592.12 that was forcefully extracted from me in order to complete the return portion of my trip.  In addition to being an unreasonable and unethical charge the whole incident  caused me considerable grief and hardship.  Please let me know how American Airlines will be refunding me this charge. 

#AA.com response

February 12, 2015
Dear Dr. Milstead:
Thank you for contacting American. I regret any misunderstanding regarding the name in which your ticket was issued.
For identification purposes, the Transportation Security Administration (TSA) has long required that travelers must present state or government
issued photo identification that matches the name of the ticket. With the introduction of the TSA Secure Flight Program, this requirement now
extends to international travel and tickets must be issued in the name that matches the documents that will be presented as proof of citizenship,
residency and identity. This is a joint effort of TSA and Customs and Border Protection (CBP) but transitioning the responsibility of
documentation verification to TSA allows CBP to more effectively focus on its core mission of border enforcement and protection, while allowing
TSA to more effectively fulfill its mission of ensuring aviation security.
We generally will permit a name correction without charge as an exception. However, we can only do so when American is the only operating
airline on the itinerary. When other airlines are booked on the ticket, we are unable to make such an exception and the applicable fare rules
apply to any ticketing changes. This appears to be the reason you were charged this fee and for this reason we regrettably deny your request
for a refund of this charge.
We want travel on American to be pleasant and trouble-free, and I'm sorry that your check-in did not proceed smoothly as a result of the name
discrepancy. Dr. Milstead, we'll look forward to welcoming you aboard again soon.
Sincerely,
Tracie Lager
Customer Relations
American Airlines
AA Ref#1-2920444650 

February 12, 2015-My reply to American Airlines by Fax
-------------------------
#My fax to AA.com

Fax: 480-693-2300

American Airlines Customer Relations

American Airlines: I received the email message below on February 12, 2015 from AA concerning a disputed charge. I
find it interesting that there is no way to respond to this message nor are there instructions given on how to protest the
response. AA does not provide a means to respond except perhaps by mail or fax. So I am faxing this to you in the
hopes that someone will respond. If I do not get a response I will continue efforts to find a way to contact you. I will
also be sending a copy of this fax by email to the travel agent who booked the flight, Viviana Merino of Travel Security in
Santiago Chile (vmerino@security.cl, telephone: 56 2 5843400)
Here are the facts:
1. I traveled to on USAir/American Airlines on the 16th of January 2015 on flights AA3827, AA711, and AA225 without
incident
2. Before traveling I called AA to confirmed my flight, add my frequent flyer number, and ask for a vegetarian meal. At
that time no problems were found.
3. The day of my return, February 7, 2015, I attempted to use the online check in service on AA.com. I was surprised to
find that the ticket was not available under my Frequent Flyer number but it was found when I searched for the flight
and the confirmation number (ZIEGRS). When I attempted to complete the online check in I was asked for additional
information such as my middle name. It should be noted however, MY FULL NAME WAS CORRECTLY DISPLAYED ON THE
ORIGINAL TICKET. For some reason the online check in was unsuccessful. No reason was given and I was directed to see
an agent. At no time did I request or authorize any changes to my ticket nor was I warned that using the online check in
could result in changes that would incur any charges.
4. When I arrived at the airport two hours before my flight I was told that I needed to pay a substantial penalty of
$592.12 (371.200 pesos Chilenos) in order to board the flight. The agent could not explain what the charge was for nor
could her supervisor Luis Gajardo. I asked Sr. Gajardo to call American Airlines to get more information and he informed
me that: He was the supervisor and would not call anyone and that if I wanted to fly I would need to pay the penalty .
Since I did not have a cellphone I asked him to call the travel agent (who I later learned had an office in the airport) and
he told me that he would not authorize any calls. I must say I was shocked by his indifference to my situation and his
total lack of interest in trying to find a solution.
5. Since I was in a foreign country, with no place to stay, and a need to get home to return to my work and family
obligations I agreed to pay the penalty under protest. Then ensued the next debacle. It took the agent, and later, the
supervisor over an hour to figure out how to charge my debit card during which time my flight left and I was rebooked
on a later flight; missing my connections and losing my vegetarian meal.
6. The agent told me I would be able to protest the charge on AA.com using the inflight wireless, a service that was not
available on the flight. So I was not able to send in a protest until I returned home.
I am somewhat mystified by the response I received from Tracie Lager (see below). It does not appear that Tracie
actually investigated the incident for the following reasons.
1. My name was correct on the original ticket and no requests were made to change it. 2. American Airlines and USair were the only carriers and they have merged so this should not restrict the ability of
American to make a refund.
Here is what I’d like to know.
1. What was the reason for the charge?
2. Who authorized the charge?
3. What changes were made to the ticket?
4. Who authorized the changes?
5. Which additional carriers were involved that prevented a refund?
6. How can I contact you more efficiently: a direct phone line or email address?
7. What are the steps available to me to resolve this situation?
I will expect a response by email within 24 hours.
William Bryan Milstead

#AA.com response
February  14, 2015



Dear Dr. Milstead:


Thank you for your additional email. We are sorry you were disappointed that you couldn't 'reply' to our previous email message. We very much appreciate any comments you have for us and to ensure the efficient receipt and timely handling of multiple messages from our customers, we ask that replies be sent via www.aa.com/customerrelations.

Upon further research, our records indicate that your name change was actually done back in December 2014. Further research indicates that you were booked to travel on AA912 from Santiago Chile to Miami on 02/07/15 but you were rebooked on later flight AA226.

To ensure a smooth trip, we strongly advise that our customers traveling to international destinations check in for their flights well in advance of the scheduled departure time. The specific recommended check-in time varies depending on the international destination. You can find complete information about the check-in requirements on AA.com or by clicking the following link: www.aa.com/arrivaltimes. This check-in policy is necessary to ensure that there is ample time to complete the special requirements of international travel, such as checking documents and completing baggage security procedures.

We can only presume that because you may have missed the cutoff check in time for flight AA912 you were rebooked on AA226. When these situations occur, we will rebook customers on an alternate flight after applying the applicable fare difference and/or change charge.

Since we don't have the benefit of actually being at the airport -- as our airport agents, it wouldn't be appropriate for us to second-guess what occurred with the situation you described. We apologize for any inconvenience.



Sincerely,




Lucecita Karim

Customer Relations

American Airlines


AA Ref#1-2935112143

The information in this email is confidential and is intended solely for the addressee(s); access to anyone else is unauthorized. If this message has been sent to you in error, do not review, disseminate, distribute or copy it. If you are not the intended recipient, please delete this email from your email system.


RESPCONID: 1-1CQ2UXX:

RESPID:1-1CQ2UXV:

TID:1-1CJHN0V:

PROCESS:Response:

CONTACTID:1-1CAR9IF:


NOTICE: This email and any attachments are for the exclusive and confidential use of the intended recipient(s). If you are not an intended recipient, please do not read, distribute, or take action in reliance upon this message. If you have received this in error, please notify me immediately by return email and promptly delete this message and its attachments from your computer.

February 15, 2015-Third Communication sent to AA.com
-------------------------
#My message to AA.com on http://www.aa.com/contactAA/viewEmailFormAccess.do?eventName=customerRelations



This is my third attempt to get information on why I was charged nearly $600 extra to board my flight.  In response to your latest response to my messages:  I am not asking you to “second guess” the gate agent.  The charge was assigned by the computer system prior to my talking to the gate agent.  I arrived two hours early for the flight.  The charge was not related to rebooking the flight.  So instead of stonewalling or blame shifting let’s start here:  What was the charge for?  When was the charge made?  Who authorized the charge? To assist you in this I have conveniently compiled the previous correspondence with AA in this public document: https://github.com/willbmisled/AmericanAirlines/blob/master/ComplaintHistory.md  Please read this completely and research you answer carefully before responding-but I will expect a response within 24 hours.  Please also send me a phone number the person who responds so we can talk directly. 

                                                       



